const STORAGE_KEY = 'boss-creator-v1';
const MOVE_LIST_URL = 'https://pokeapi.co/api/v2/move?limit=1000';
const MOVE_API = 'https://pokeapi.co/api/v2/move/';
const SPRITE = id => `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
const GAMES = [['Gen 1','Pokémon Rojo','Pokémon Azul','Pokémon Amarillo'],['Gen 2','Pokémon Oro','Pokémon Plata','Pokémon Cristal'],['Gen 3','Pokémon Rubí','Pokémon Zafiro','Pokémon Esmeralda','Pokémon Rojo Fuego','Pokémon Verde Hoja'],['Gen 4','Pokémon Diamante','Pokémon Perla','Pokémon Platino','Pokémon Oro HeartGold','Pokémon Plata SoulSilver'],['Gen 5','Pokémon Negro','Pokémon Blanco','Pokémon Negro 2','Pokémon Blanco 2'],['Gen 6','Pokémon X','Pokémon Y','Pokémon Rubí Omega','Pokémon Zafiro Alfa'],['Gen 7','Pokémon Sol','Pokémon Luna','Pokémon UltraSol','Pokémon UltraLuna','Pokémon: Let’s Go, Pikachu!','Pokémon: Let’s Go, Eevee!']].flatMap(([gen,...games])=>games.map(game=>({gen,game})));
const state={screen:'home',gameId:null,bossId:null,editingPokemonId:null,modal:null,moveNames:[],moveCache:{},moveLoading:false,draftPhoto:null};
const app=document.getElementById('app'),toastEl=document.getElementById('toast');let store=loadStore();
function loadStore(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{games:[]}}catch{return{games:[]}}}function saveStore(){localStorage.setItem(STORAGE_KEY,JSON.stringify(store))}function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}function esc(v=''){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2200)}function currentGame(){return store.games.find(g=>g.id===state.gameId)}function currentBoss(){return currentGame()?.bosses.find(b=>b.id===state.bossId)}function findPokemon(name){return window.POKEMON_DATA?.find(p=>p.name===name)}
function pokemonSprite(p){if(!p)return SPRITE(1);if(Number(p.id)<=721)return SPRITE(Number(p.id));const baseName=String(p.name).replace(/ \d+$/,'');const base=window.POKEMON_DATA?.find(x=>x.id<=721&&x.name===baseName);return SPRITE(base?.id||1)}
function render(){app.innerHTML=`<div class="app-shell">${sidebar()}<main class="main"><div class="topbar">${topbar()}</div><div class="content">${screen()}</div></main></div>${modal()}`;bind();if(state.screen==='boss'&&currentBoss()?.pokemon?.length)buildGuide().then(html=>{const c=document.querySelector('.content');if(c&&!document.getElementById('guide'))c.insertAdjacentHTML('beforeend',html)})}
function sidebar(){return `<aside class="sidebar"><div class="brand">Boss <span>Creator</span></div><div class="subtitle">Nuzlocke Tracker · Gen 1–7</div><button class="btn btn-primary" style="width:100%" data-action="new-game">＋ New Game</button><div class="side-section-title">Guardados</div><div class="save-list">${store.games.length?store.games.map(g=>`<button class="save-item ${g.id===state.gameId?'active':''}" data-game="${g.id}"><strong>${esc(g.name)}</strong><small>${esc(g.gen)} · ${g.bosses.length} boss${g.bosses.length===1?'':'es'}</small></button>`).join(''):`<div class="empty">Aquí aparecerán tus partidas.</div>`}</div></aside>`}
function topbar(){const g=currentGame(),b=currentBoss();return g?`<div class="crumb">${esc(g.name)} ${b?'› '+esc(b.name):''}</div><div>${b?`<button class="btn btn-secondary" data-action="back-game">← Partida</button>`:''}</div>`:`<div class="crumb">Inicio</div><div></div>`}
function screen(){if(state.screen==='home')return homeScreen();if(state.screen==='game')return gameScreen();if(state.screen==='boss')return bossScreen();return homeScreen()}
function homeScreen(){return `<section class="hero"><h1>Boss <span>Creator</span></h1><p>Crea tus partidas Nuzlocke, organiza líderes, rivales, Alto Mando y equipos enemigos, y genera una guía visual de cada combate.</p><button class="btn btn-primary" data-action="new-game">New Game</button></section><div class="grid grid-2"><div class="card"><h2 style="margin-top:0">Qué incluye</h2><p>Pokémon de las generaciones 1–7, megas y formas primigenias seleccionadas, movesets de cuatro movimientos, habilidad, objeto, nivel y estadísticas de Gen VII.</p></div><div class="card"><h2 style="margin-top:0">Guardado local</h2><p>Tus partidas se guardan automáticamente en este navegador. Las fotos de los bosses también se conservan localmente.</p></div></div>`}
function gameScreen(){const g=currentGame();return `<div class="section-title"><div><h2>${esc(g.name)}</h2><div style="color:#777;font-size:13px">${esc(g.gen)}</div></div><button class="btn btn-primary" data-action="create-boss">＋ Crear boss</button></div><div class="boss-grid">${g.bosses.length?g.bosses.map(bossCard).join(''):`<div class="card" style="grid-column:1/-1;text-align:center"><h3>Aún no hay bosses</h3><p style="color:#777">Crea el primero con el botón de arriba.</p><button class="btn btn-primary" data-action="create-boss">Crear boss</button></div>`}</div>`}
function bossCard(b){return `<article class="boss-card" data-boss="${b.id}"><div class="boss-photo">${b.photo?`<img src="${b.photo}" alt="">`:`<div class="boss-placeholder">👤</div>`}</div><div class="boss-body"><span class="badge">${esc(b.type)}</span><h3>${esc(b.name)}</h3><small>${b.pokemon.length} Pokémon · ${b.finished?'Guía terminada':'En edición'}</small></div></article>`}
function bossScreen(){const b=currentBoss();if(!b)return gameScreen();if(b.finished)return finishedBossScreen(b);return `<div class="section-title"><div><h2>${esc(b.name)}</h2><div style="color:#777;font-size:13px">${esc(b.type)}</div></div><div class="actions" style="margin:0"><button class="btn btn-secondary" data-action="back-game">← Partida</button><button class="btn btn-secondary" data-action="edit-boss">Editar boss</button><button class="btn btn-primary" data-action="add-pokemon">＋ Agregar Pokémon</button><button class="btn btn-primary" data-action="finish">Finish</button></div></div><div class="card" style="margin-bottom:18px"><div style="display:flex;gap:18px;align-items:center">${b.photo?`<img src="${b.photo}" style="width:80px;height:80px;object-fit:cover;border-radius:12px">`:'<div class="boss-placeholder" style="font-size:40px">👤</div>'}<div><strong>${esc(b.name)}</strong><div style="color:#777;font-size:13px">${b.pokemon.length} Pokémon configurados</div></div></div></div><div class="pokemon-list">${b.pokemon.length?b.pokemon.map(pokemonRow).join(''):`<div class="card" style="text-align:center;color:#888">Añade Pokémon para construir el equipo.</div>`}</div>`}
function finishedBossScreen(b){return `<div class="section-title"><div><h2>${esc(b.name)}</h2><div style="color:#777;font-size:13px">${esc(b.type)} · Guía final</div></div><div class="actions" style="margin:0"><button class="btn btn-secondary" data-action="back-game">← Partida</button><button class="btn btn-primary" data-action="edit-boss">Editar</button></div></div><div class="card"><div style="display:flex;gap:18px;align-items:center">${b.photo?`<img src="${b.photo}" style="width:80px;height:80px;object-fit:cover;border-radius:12px">`:'<div class="boss-placeholder" style="font-size:40px">👤</div>'}<div><strong>${esc(b.name)}</strong><div style="color:#777;font-size:13px">Guía guardada · ${b.pokemon.length} Pokémon</div></div></div></div>`}
function pokemonRow(p){const mon=findPokemon(p.name);return `<div class="pokemon-row"><img class="sprite" src="${pokemonSprite(mon)}" alt=""><div class="pokemon-info"><h3>${esc(p.name)} <span style="font-weight:500;color:#777">Nv. ${p.level}</span></h3><div>${(mon?.type||'').split('/').map(t=>`<span class="type-pill">${esc(t)}</span>`).join('')} <span class="type-pill">${esc(p.ability||'Sin habilidad')}</span></div><small style="color:#777">${(p.moves||[]).filter(Boolean).length}/4 movimientos · ${p.item?esc(p.item):'Sin objeto'}</small></div><div class="pokemon-actions"><button class="btn btn-secondary" data-edit-pokemon="${p.id}">Editar</button><button class="btn btn-danger" data-delete-pokemon="${p.id}">Eliminar</button></div></div>`}
function modal(){if(!state.modal)return '';if(state.modal==='game')return `<div class="modal-backdrop open"><div class="modal"><h2>New Game</h2><div class="field"><label>Elige un juego</label><select id="gameSelect">${GAMES.map(g=>`<option value="${esc(g.game)}">${esc(g.gen)} · ${esc(g.game)}</option>`).join('')}</select></div><div class="actions"><button class="btn btn-secondary" data-action="close-modal">Cancelar</button><button class="btn btn-primary" data-action="save-game">Create Game</button></div></div></div>`;if(state.modal==='boss')return bossModal();if(state.modal==='pokemon')return pokemonModal();return ''}
function bossModal(){const b=currentBoss(),editing=!!b;return `<div class="modal-backdrop open"><div class="modal"><h2>${editing?'Editar boss':'Crear boss'}</h2><div class="grid grid-2"><div class="field"><label>Tipo</label><select id="bossType">${['Elite Four / Campeón','Líder de Gimnasio','Rival','Equipo Enemigo'].map(x=>`<option ${b?.type===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Nombre</label><input id="bossName" value="${esc(b?.name||'')}" placeholder="Ej. Lance"></div></div><div class="field" style="margin-top:14px"><label>Foto del boss</label><input id="bossPhoto" type="file" accept="image/*"><div id="photoPreview" class="file-preview">${b?.photo?`<img src="${b.photo}" alt="">`:'Selecciona una imagen (opcional)'}</div></div><div class="actions"><button class="btn btn-secondary" data-action="close-modal">Cancelar</button><button class="btn btn-primary" data-action="save-boss">${editing?'Guardar cambios':'Crear boss'}</button></div></div></div>`}
function pokemonModal(){const b=currentBoss(),p=b?.pokemon.find(x=>x.id===state.editingPokemonId),editing=!!p,mon=findPokemon(p?.name||'Bulbasaur');const abilities=(mon?.abilities||[]).map(a=>`<option ${p?.ability===a?'selected':''}>${esc(a)}</option>`).join('');return `<div class="modal-backdrop open"><div class="modal"><h2>${editing?'Editar Pokémon':'Agregar Pokémon'}</h2><div class="form-row"><div class="field"><label>Pokémon</label><input id="pokeName" list="pokemonList" value="${esc(p?.name||'')}" placeholder="Busca y selecciona"><datalist id="pokemonList">${(window.POKEMON_DATA||[]).map(x=>`<option value="${esc(x.name)}">${esc(x.form||'')}</option>`).join('')}</datalist></div><div class="field"><label>Nivel</label><input id="pokeLevel" type="number" min="1" max="100" value="${p?.level||50}"></div></div><div class="form-row" style="margin-top:14px"><div class="field"><label>Habilidad</label><select id="pokeAbility">${abilities||'<option value="">Selecciona primero el Pokémon</option>'}</select></div><div class="field"><label>Objeto</label><input id="pokeItem" value="${esc(p?.item||'')}" placeholder="Ej. Restos"></div></div><div style="margin-top:18px"><div class="section-title"><h2 style="font-size:16px">Moveset</h2><span class="badge">4 espacios</span></div><div class="move-form">${[0,1,2,3].map(i=>moveField(i,p?.moves?.[i]||'')).join('')}</div></div><div class="notice" style="margin-top:16px">Los movimientos disponibles son los introducidos hasta la Generación VII. Al seleccionarlos se consulta su potencia y categoría.</div><div class="actions"><button class="btn btn-secondary" data-action="close-modal">Cancelar</button><button class="btn btn-primary" data-action="save-pokemon">${editing?'Guardar Pokémon':'Agregar Pokémon'}</button></div></div></div>`}
function moveField(i,value){return `<div class="field"><label>Movimiento ${i+1}</label><input class="move-input" data-move-index="${i}" list="moveList" value="${esc(value)}" placeholder="Buscar movimiento"><datalist id="moveList">${state.moveNames.map(m=>`<option value="${esc(m.name)}">`).join('')}</datalist></div>`}
async function loadMoves(){if(state.moveNames.length||state.moveLoading)return;state.moveLoading=true;try{const r=await fetch(MOVE_LIST_URL);const d=await r.json();state.moveNames=d.results.map(m=>({id:Number(m.url.split('/').filter(Boolean).pop()),name:m.name})).filter(m=>m.id>0&&m.id<=728)}catch{toast('No se pudo cargar la lista de movimientos. Revisa la conexión.')}state.moveLoading=false}
async function getMove(name){if(!name)return null;if(state.moveCache[name])return state.moveCache[name];try{const r=await fetch(MOVE_API+encodeURIComponent(name));const d=await r.json();state.moveCache[name]=d;return d}catch{return null}}
function gen7Move(d){if(!d)return{power:null,category:'status',type:'Normal',display:'—'};let power=d.power;const pv=(d.past_values||[]).find(x=>x.generation?.name==='generation-viii');if(pv&&pv.power!==null&&pv.power!==undefined)power=pv.power;return{power,category:d.damage_class?.name||'status',type:d.type?.name||'normal',display:power==null?'—':power}}
function categoryLabel(c){return c==='physical'?'Physical':c==='special'?'Special':'Status'}function title(s){return String(s||'').replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}function prettyMove(s){return title(s)}
function bind(){document.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',()=>action(el.dataset.action)));document.querySelectorAll('[data-game]').forEach(el=>el.addEventListener('click',()=>{state.gameId=el.dataset.game;state.screen='game';state.bossId=null;render()}));document.querySelectorAll('[data-boss]').forEach(el=>el.addEventListener('click',()=>{state.bossId=el.dataset.boss;state.screen='boss';render()}));document.querySelectorAll('[data-edit-pokemon]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();state.editingPokemonId=el.dataset.editPokemon;state.modal='pokemon';loadMoves().then(render)}));document.querySelectorAll('[data-delete-pokemon]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();deletePokemon(el.dataset.deletePokemon)}));const file=document.getElementById('bossPhoto');if(file)file.addEventListener('change',handlePhoto);const poke=document.getElementById('pokeName');if(poke)poke.addEventListener('change',syncAbilities)}
function action(a){if(a==='new-game'){state.modal='game';render()}else if(a==='close-modal'){state.modal=null;state.editingPokemonId=null;state.draftPhoto=null;render()}else if(a==='save-game')saveGame();else if(a==='create-boss'){state.modal='boss';state.bossId=null;state.draftPhoto=null;render()}else if(a==='save-boss')saveBoss();else if(a==='add-pokemon'){state.editingPokemonId=null;state.modal='pokemon';loadMoves().then(render)}else if(a==='save-pokemon')savePokemon();else if(a==='edit-boss'){const b=currentBoss();if(b){b.finished=false;saveStore()}state.modal=null;state.draftPhoto=null;render()}else if(a==='back-game'){state.screen='game';state.bossId=null;render()}else if(a==='finish')finishBoss()}
function saveGame(){const name=document.getElementById('gameSelect').value;const g={id:uid(),name,gen:GAMES.find(x=>x.game===name)?.gen||'',bosses:[]};store.games.push(g);saveStore();state.gameId=g.id;state.screen='game';state.modal=null;render();toast('Partida creada')}
function handlePhoto(e){const f=e.target.files?.[0];if(!f)return;const img=new Image();img.onload=()=>{const c=document.createElement('canvas'),max=900,scale=Math.min(1,max/img.width);c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);state.draftPhoto=c.toDataURL('image/jpeg',.82);const p=document.getElementById('photoPreview');if(p)p.innerHTML=`<img src="${state.draftPhoto}" alt="">`};img.src=URL.createObjectURL(f)}
function saveBoss(){const g=currentGame(),name=document.getElementById('bossName').value.trim();if(!name)return toast('Pon un nombre al boss');const type=document.getElementById('bossType').value,existing=g.bosses.find(b=>b.id===state.bossId);if(existing){existing.name=name;existing.type=type;if(state.draftPhoto!==null)existing.photo=state.draftPhoto}else{const b={id:uid(),name,type,photo:state.draftPhoto||null,pokemon:[],finished:false};g.bosses.push(b);state.bossId=b.id;state.screen='boss'}saveStore();state.modal=null;state.draftPhoto=null;render();toast(existing?'Boss actualizado':'Boss creado')}
function syncAbilities(){const p=findPokemon(document.getElementById('pokeName').value.trim()),s=document.getElementById('pokeAbility');if(!s)return;s.innerHTML=(p?.abilities||[]).map(a=>`<option>${esc(a)}</option>`).join('')||'<option value="">Selecciona un Pokémon</option>'}
function savePokemon(){const b=currentBoss(),name=document.getElementById('pokeName').value.trim(),mon=findPokemon(name);if(!mon)return toast('Selecciona un Pokémon válido de la lista');const level=Math.max(1,Math.min(100,Number(document.getElementById('pokeLevel').value)||50)),ability=document.getElementById('pokeAbility').value,item=document.getElementById('pokeItem').value.trim(),moves=[...document.querySelectorAll('.move-input')].map(x=>x.value.trim());const invalid=moves.filter(Boolean).find(x=>!state.moveNames.some(m=>m.name===x));if(invalid)return toast('Selecciona los movimientos de la lista');const obj={id:state.editingPokemonId||uid(),name,level,ability,item,moves};if(state.editingPokemonId){const idx=b.pokemon.findIndex(x=>x.id===state.editingPokemonId);b.pokemon[idx]=obj}else b.pokemon.push(obj);saveStore();state.modal=null;state.editingPokemonId=null;render();toast('Pokémon guardado')}
function deletePokemon(id){const b=currentBoss();b.pokemon=b.pokemon.filter(p=>p.id!==id);b.finished=false;saveStore();render();toast('Pokémon eliminado')}
function finishBoss(){const b=currentBoss();if(!b.pokemon.length)return toast('Añade al menos un Pokémon antes de Finish');b.finished=true;saveStore();render();setTimeout(()=>document.getElementById('guide')?.scrollIntoView({behavior:'smooth'}),30);toast('Guía generada')}
async function buildGuide(){const b=currentBoss();if(!b)return '';const cards=[];for(const p of b.pokemon){const mon=findPokemon(p.name),details=await Promise.all((p.moves||[]).map(getMove)),moves=(p.moves||[]).map((name,i)=>({name,d:gen7Move(details[i])}));cards.push(`<article class="guide-card"><div class="guide-head"><div class="level">Level <strong>${p.level}</strong></div><h3>${esc(p.name)}</h3><div class="ability">${esc(p.ability||'Sin habilidad')}</div><img class="poke-sprite" src="${pokemonSprite(mon)}" alt=""></div><div class="guide-body"><div class="guide-moves">${moves.map(m=>`<div class="guide-move">${m.name?`<div class="move-name">${esc(prettyMove(m.name))} <span class="move-power">✕${m.d.display}</span></div><div class="sub"><span class="move-chip type">${esc(title(m.d.type))}</span><span class="move-chip category">${esc(categoryLabel(m.d.category))}</span></div>`:'<div class="empty-moves">—</div>'}</div>`).join('')}</div><div class="item-line"><strong>Objeto:</strong> ${esc(p.item||'—')}</div><div class="stats" style="margin-top:14px">${['HP','ATK','DEF','SPA','SPD','SPE'].map((n,i)=>`<div class="stat"><span class="stat-name">${n.toLowerCase()}</span><span class="stat-value">${mon?.stats?.[i]??'—'}</span><div class="bar"><span style="width:${Math.min(100,((mon?.stats?.[i]||0)/255)*100)}%"></span></div></div>`).join('')}</div></div></article>`)}return `<section id="guide" style="margin-top:28px"><div class="section-title"><h2>Guía del combate</h2><span class="badge">${b.pokemon.length} Pokémon</span></div><div class="guide">${cards.join('')}</div></section>`}
loadMoves();render();
