(function(){
const TYPE_COLORS={normal:'#A8A77A',fire:'#EE8130',water:'#6390F0',electric:'#F7D02C',grass:'#7AC74C',ice:'#96D9D6',fighting:'#C22E28',poison:'#A33EA1',ground:'#E2BF65',flying:'#A98FF3',psychic:'#F95587',bug:'#A6B91A',rock:'#B6A136',ghost:'#735797',dragon:'#6F35FC',dark:'#705746',steel:'#B7B7CE',fairy:'#D685AD'};
const STAT_KEYS=[['HP','hp'],['Atk','attack'],['Def','defense'],['SpA','special-attack'],['SpD','special-defense'],['Spe','speed']];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=s=>String(s||'').replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const slug=s=>String(s||'').toLowerCase().replace(/\s+/g,'-').replace(/[.'’]/g,'').replace(/-+/g,'-');
const typeColor=t=>TYPE_COLORS[String(t||'').toLowerCase()]||'#777';
const sprite=p=>{if(!p)return '';const id=Number(p.id);if(id<=721)return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;const base=(window.POKEMON_DATA||[]).find(x=>x.name===p.name);return base?`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${base.id}.png`:''};
function getStats(mon){const arr=mon?.stats||[];return {hp:arr[0]||0,attack:arr[1]||0,defense:arr[2]||0,'special-attack':arr[3]||0,'special-defense':arr[4]||0,speed:arr[5]||0};}
function statTotal(st){return Object.values(st).reduce((a,b)=>a+Number(b||0),0)}
async function moveData(name){if(!name)return null;try{if(window.getMove)return await window.getMove(name);const r=await fetch('https://pokeapi.co/api/v2/move/'+encodeURIComponent(name));return await r.json()}catch{return null}}
function categoryIcon(cat){const c=cat==='physical'?'physical':cat==='special'?'special':'status';return `<span class="move-category-icon ${c}" title="${title(c)}" aria-label="${title(c)}"></span>`}
async function card(p){
 const mon=window.POKEMON_RUNTIME?.details?await window.POKEMON_RUNTIME.details(slug(p.name)):((window.POKEMON_DATA||[]).find(x=>x.name===p.name));
 const st=getStats(mon),total=statTotal(st),moves=await Promise.all((p.moves||[]).slice(0,4).map(moveData));
 const moveHtml=(p.moves||[]).slice(0,4).map((m,i)=>{const d=moves[i],power=d?.power??'—',typ=d?.type?.name||'normal',cat=d?.damage_class?.name||'status';return `<div class="guide-move"><div class="move-name-row"><span class="move-name">${esc(title(m))}</span><span class="move-power-inline">${esc(power)}</span></div><div class="move-meta"><span class="move-type" style="background:${typeColor(typ)}">${esc(title(typ))}</span>${categoryIcon(cat)}</div></div>`}).join('');
 const statHtml=STAT_KEYS.map(([label,key])=>{const val=st[key]||0,pct=Math.min(100,(val/180)*100);return `<div class="guide-stat"><div class="stat-label"><span>${label}</span><b>${val}</b></div><div class="stat-bar"><i style="width:${pct}%"></i></div></div>`}).join('');
 const types=(mon?.type||'').split(' / ').map(t=>`<span class="guide-type" style="background:${typeColor(t)}">${esc(t)}</span>`).join('');
 return `<article class="guide-card"><div class="guide-top"><div class="guide-info"><div class="guide-name-row">${types}<span class="guide-level">Lv. ${esc(p.level||50)}</span></div><h3>${esc(p.name)}</h3><div class="guide-detail"><span><b>Ability</b> ${esc(p.ability||'—')}</span><span><b>Item</b> <span class="item-icon">🎒</span> ${esc(p.item||'—')}</span></div></div><div class="guide-visual"><img src="${sprite(mon)}" alt="${esc(p.name)}"><div class="bst"><small>BASE STAT TOTAL</small><strong>${total}</strong></div></div></div><div class="guide-bottom"><div class="guide-moves">${moveHtml}</div><div class="guide-stats"><div class="stats-title">STATS</div>${statHtml}</div></div></article>`;
}
window.buildGuide=async function(){const b=window.currentBoss?.();if(!b)return '';const cards=await Promise.all((b.pokemon||[]).map(card));return `<div id="guide" class="boss-guide">${cards.join('')}</div>`};
window.finishedBossScreen=function(b){return `<div class="section-title"><div><h2>${esc(b.name)}</h2><div style="color:#777;font-size:13px">${esc(b.type)} · Guía final</div></div><div class="actions" style="margin:0"><button class="btn btn-secondary" data-action="back-game">← Partida</button><button class="btn btn-primary" data-action="edit-boss">Editar</button></div></div><div class="guide-boss-head">${b.photo?`<img src="${b.photo}" alt="">`:''}<div><span>${esc(b.type)}</span><strong>${esc(b.name)}</strong><small>${b.pokemon.length} Pokémon</small></div></div><div id="guide" class="boss-guide"></div>`};
})();