(function(){
const KEY='boss-creator-v1';
const TYPES={normal:'#A8A77A',fire:'#EE8130',water:'#6390F0',electric:'#F7D02C',grass:'#7AC74C',ice:'#96D9D6',fighting:'#C22E28',poison:'#A33EA1',ground:'#E2BF65',flying:'#A98FF3',psychic:'#F95587',bug:'#A6B91A',rock:'#B6A136',ghost:'#735797',dragon:'#6F35FC',dark:'#705746',steel:'#B7B7CE',fairy:'#D685AD'};
const ST=[['HP',0],['Atk',1],['Def',2],['SpA',3],['SpD',4],['Spe',5]];
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const pretty=s=>String(s||'').replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const color=t=>TYPES[String(t||'').toLowerCase()]||'#777';
function ctx(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{"games":[]}');const gid=sessionStorage.getItem('bc-game-id'),bid=sessionStorage.getItem('bc-boss-id');let g=s.games?.find(x=>x.id===gid)||s.games?.find(x=>x.name==='Pokémon Zafiro Alfa — Combates');let b=g?.bosses?.find(x=>x.id===bid);if(!b){const crumb=document.querySelector('.crumb')?.textContent||'',name=crumb.split('›')[1]?.trim();b=g?.bosses?.find(x=>x.name===name)}return g&&b?{s,g,b}:null}catch{return null}}
async function details(name){const p=(window.POKEMON_DATA||[]).find(x=>x.name===name);const slug=p?.slug||String(name).toLowerCase().replace(/ /g,'-');try{if(window.POKEMON_RUNTIME?.details)return await window.POKEMON_RUNTIME.details(slug);const r=await fetch('https://pokeapi.co/api/v2/pokemon/'+encodeURIComponent(slug));const d=await r.json();let stats=d.stats.map(x=>x.base_stat);if(window.MODIFIED_STATS?.[d.id])stats=window.MODIFIED_STATS[d.id];return{name:d.name,id:d.id,type:d.types.map(x=>pretty(x.type.name)).join(' / '),stats,slug:d.name}}catch{return null}}
async function move(n){try{if(window.getMove)return await window.getMove(n);const r=await fetch('https://pokeapi.co/api/v2/move/'+encodeURIComponent(n));return await r.json()}catch{return null}}
async function loc(k,n){try{return window.PokemonES?.names?await window.PokemonES.names(k,n):n}catch{return n}}
function statClass(v){return v<=59?'stat-red':v<=79?'stat-orange':v<=99?'stat-yellow':v<=129?'stat-green':'stat-dark-green'}
async function card(p){const m=await details(p.name),st=m?.stats||[0,0,0,0,0,0],total=st.reduce((a,v)=>a+Number(v||0),0),ms=await Promise.all((p.moves||[]).slice(0,4).map(move)),mn=await Promise.all((p.moves||[]).slice(0,4).map(x=>loc('move',x))),ab=await loc('ability',p.ability||''),it=await loc('item',p.item||'');const moves=(p.moves||[]).slice(0,4).map((x,i)=>{const d=ms[i],cat=d?.damage_class?.name||'status',power=d?.power??'—',typ=d?.type?.name||'normal';return `<div class="guide-move"><div class="move-name-row"><span class="move-name">${esc(mn[i]||x)}</span><span class="move-power-inline">${esc(power)}</span></div><div class="move-meta"><span class="move-type" style="background:${color(typ)}">${esc(pretty(typ))}</span><span class="move-category-icon ${cat}" title="${esc(pretty(cat))}"></span></div></div>`}).join('');const stats=ST.map(([n,i])=>{const v=Number(st[i]||0);return `<div class="guide-stat"><div class="stat-label"><span>${n}</span><b>${v}</b></div><div class="stat-bar"><i class="${statClass(v)}" style="width:${Math.min(100,v/180*100)}%"></i></div></div>`}).join('');const types=(m?.type||'').split(' / ').map(t=>`<span class="guide-type" style="background:${color(t)}">${esc(t)}</span>`).join('');return `<article class="guide-card"><div class="guide-top"><div class="guide-info"><div class="guide-name-row">${types}<span class="guide-level">Lv. ${esc(p.level||50)}</span></div><h3>${esc(p.name)}</h3><div class="guide-detail"><span><b>Habilidad</b> ${esc(ab||p.ability||'—')}</span><span><b>Objeto</b> 🎒 ${esc(it||p.item||'—')}</span></div></div><div class="guide-visual"><img src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${m?.id||1}.png" alt="${esc(p.name)}"><div class="bst"><small>BASE STAT TOTAL</small><strong>${total}</strong></div></div></div><div class="guide-bottom"><div class="guide-moves">${moves}</div><div class="guide-stats"><div class="stats-title">STATS</div>${stats}</div></div></article>`}
window.buildGuide=async function(){const c=ctx();if(!c)return '';const html=await Promise.all((c.b.pokemon||[]).map(card));return `<div id="guide" class="boss-guide">${html.join('')}</div>`};
document.addEventListener('click',e=>{const b=e.target.closest('[data-boss]'),g=e.target.closest('[data-game]');if(b)sessionStorage.setItem('bc-boss-id',b.dataset.boss);if(g)sessionStorage.setItem('bc-game-id',g.dataset.game)},true);
const obs=new MutationObserver(()=>{const c=ctx();if(!c||!c.b.name.startsWith('Aura')||!c.b.variants)return;const content=document.querySelector('.content');if(!content||content.querySelector('.aura-variants'))return;const box=document.createElement('div');box.className='card aura-variants';box.innerHTML='<strong>Variante</strong><div class="actions" style="margin:10px 0 0">'+[['fire','🔥 Fuego'],['water','💧 Agua'],['leaf','🍃 Hoja']].map(([k,l])=>`<button class="btn ${c.b.activeVariant===k?'btn-primary':'btn-secondary'}" data-aura="${k}">${l}</button>`).join('')+'</div>';content.prepend(box);box.querySelectorAll('[data-aura]').forEach(x=>x.onclick=()=>{const k=x.dataset.aura;c.b.activeVariant=k;c.b.pokemon=c.b.variants[k].pokemon;localStorage.setItem(KEY,JSON.stringify(c.s));location.reload()})});obs.observe(document.body,{childList:true,subtree:true});
})();